name: Update PR Description with Commits

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get PR commits and update description
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REPO_NAME=${{ github.repository }}
        TOKEN=${{ secrets.GITHUB_TOKEN }}

        # Fetch all commits in the PR
        COMMITS=$(curl -s -H "Authorization: token $TOKEN" \
          "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER/commits")
        
        # Check if we got any commits
        COMMIT_COUNT=$(echo "$COMMITS" | jq '. | length')
        if [ "$COMMIT_COUNT" -eq 0 ]; then
          echo "No commits found in this PR"
          DESCRIPTION="### No commits found in this PR"
        else
          # Create a temporary file for the description
          TEMP_FILE=$(mktemp)
          
          # Initialize the PR description with proper markdown
          echo "### Commits Included:" > "$TEMP_FILE"
          echo "" >> "$TEMP_FILE"
          
          # Process each commit
          echo "$COMMITS" | jq -r '.[] | "\(.sha)|\(.commit.message)"' | while IFS='|' read -r SHA MESSAGE; do
            # Get first line of commit message as the title
            FIRST_LINE=$(echo "$MESSAGE" | head -n 1 | xargs)
            
            # Format with SHA and first line as main bullet
            echo "* **${SHA}**: ${FIRST_LINE}" >> "$TEMP_FILE"
            
            # Get rest of the message (if any) and format as sub-bullets
            # Use a separate temp file for the remaining lines
            MSG_TEMP=$(mktemp)
            echo "$MESSAGE" | tail -n +2 | grep -v "^$" > "$MSG_TEMP"
            
            # Process each line of the remaining message
            while read -r LINE; do
              # Skip empty lines and trim whitespace
              LINE=$(echo "$LINE" | xargs)
              if [ -z "$LINE" ]; then
                continue
              fi
              
              # Add as sub-bullet with proper indentation
              echo "  * $LINE" >> "$TEMP_FILE"
            done < "$MSG_TEMP"
            
            # Clean up the message temp file
            rm "$MSG_TEMP"
            
            # Add a blank line between commits for better readability
            echo "" >> "$TEMP_FILE"
          done
          
          # Read the complete description
          DESCRIPTION=$(cat "$TEMP_FILE")
          rm "$TEMP_FILE"
        fi
        
        # Update the PR body with the commit description
        # Properly escape the description for JSON
        ESCAPED_DESCRIPTION=$(echo "$DESCRIPTION" | jq -sR .)
        
        echo "Updating PR description with:"
        echo "$DESCRIPTION"
        
        curl -X PATCH -H "Authorization: token $TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"body\":$ESCAPED_DESCRIPTION}" \
          "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER"
